[package]
name = "starry-vm"
version = "0.1.1"
edition = "2024"
authors = [
    "Mivik <mivikq@gmail.com>",
    "Asakura Mizu <asakuramizu111@gmail.com>",
]

[features]
default = ["alloc"]
alloc = []
axio = ["dep:axio"]

[dependencies]
axerrno = "0.1.0"
axio = { git = "https://github.com/Starry-Mix-THU/axio.git", rev = "4ececd3", optional = true }
bytemuck = { version = "1.23", features = [
    "align_offset",
    "const_zeroed",
    "zeroable_maybe_uninit",
] }
extern-trait = "0.1"

[dev-dependencies]
bytemuck = { version = "1.23", features = ["derive"] }
